<?php

//#######################################################################
// Extension Manager/Repository config file for ext: "jwtools2"
//
// Auto generated by Extension Builder 2016-03-29
//
// Manual updates:
// Only the data in the array - anything else is removed by next write.
// "version" and "dependencies" must not be touched!
//#######################################################################

$EM_CONF[$_EXTKEY] = [
    'title' => 'JW tools',
    'description' => 'Jwtools2 contains a scheduler task for Solr to index multiple Pagetrees and a task to execute 
        SQL-Queries. Further there are settings to enable some features in TYPO3 like showing the Page UID in Pagetree
        with a simple click in extensionmanager.',
    'category' => 'module',
    'author' => 'Stefan Froemken',
    'author_email' => 'projects@jweiland.net',
    'author_company' => 'jweiland.net',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '3.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.14-9.5.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
