services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Jwtools2\:
    resource: '../Classes/*'

  # Will be called by GeneralUtility::makeInstance in ElementBrowserController
  JWeiland\Jwtools2\Backend\Browser\FileBrowser:
    public: true

  # Will be called by GeneralUtility::makeInstance in ElementInformationController
  JWeiland\Jwtools2\Hooks\ModifyElementInformationHook:
    public: true
  # Will be called by GeneralUtility::makeInstance in AbstractLinkBrowserControler
  JWeiland\Jwtools2\Hooks\ModifyLinkHandlerHook:
    public: true

  # Will be called by GeneralUtility::makeInstance in AbstractLinkBrowserControler
  JWeiland\Jwtools2\LinkHandler\FileLinkHandler:
    public: true
  # Will be called by GeneralUtility::makeInstance in AbstractLinkBrowserControler
  JWeiland\Jwtools2\LinkHandler\FolderLinkHandler:
    public: true

